version: '2.1'
services:
#  logstash:
#    build: ./my-logstash
#    container_name: logstash-icij-nodes
#    volumes:
##      - esdata1:/usr/share/elasticsearch/data
#      - /media/john/speed/data/data:/tmp/icij/data
#    environment:
#      ELASTICSEARCH_HOST: elasticsearch
#      ELASTICSEARCH_PORT: 9200
#      HEAP_SIZE: 500m
#    networks:
#      - esnet

  elasticsearch:
    build: ./my-elasticsearch
#    container_name: elasticsearch - if you name containers you can't scale them
    mem_limit: 800m
#    ports:
#      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
##      - esdata1:/usr/share/elasticsearch/data
      - /media/john/speed/data/container-data:/usr/share/elasticsearch/data
    networks:
      - esnet
 
  kibana:
    build: ./my-kibana
    mem_limit: 800m
    networks:
      - esnet
    restart: always
    depends_on: 
      - nginx
      - elasticsearch

  nginx:
    restart: always
    build: ./my-nginx
    mem_limit: 200m 
    ports:
      - 443:443      
    volumes:
      - nginxdata:/var/log/nginx/
    networks:
      - esnet
    depends_on: 
      - elasticsearch

  setup-elastic:
    container_name: load-data
    build: ./load-data
    mem_limit: 200m  
    command: ['/bin/bash', '-c', 'cat /tmp/sample/load-data.sh | tr -d "\r" | bash']
    volumes:
      - /media/john/speed/data/data:/tmp/icij/data
    networks: 
      - esnet
    depends_on: 
      - elasticsearch

volumes:
  nginxdata:
    driver: local  

networks:
  esnet:
